# -*- coding: utf-8 -*-
"""Rondina2.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgRGUdojYs7GzbuSR5QCgQCSkhaVCeRB
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import re
import time
from datetime import datetime
import matplotlib.dates as mdates
import matplotlib.ticker as ticker
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests

count = 1
pages = 4
productos = list()
precios = list()
headers={ 'User-Agent':'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.3'}
URL = "https://www.faenzaasuncion.com/collections/all?page="
# Realizamos la petición a la web
while count <= pages:
  req = requests.get(URL+str(count), headers=headers)
  content = req.content
# Comprobamos que la petición nos devuelve un Status Code = 200
  status_code = req.status_code
  if status_code == 200:
      # Pasamos el contenido HTML de la web a un objeto BeautifulSoup()
      html = BeautifulSoup(req.text, "html.parser")
      # Obtenemos todos los divs donde están las entradas
      entradas = html.find_all('span', {'class': 'product-item__meta__inner'})
      # Recorremos todas las entradas para extraer el título, autor y fecha
      for i, entrada in enumerate(entradas):
          # Con el método "getText()" no nos devuelve el HTML
          # Sino llamamos al método "getText()" nos devuelve también el HTML
          titulo = entrada.find('p', {'class': 'product-item__title'}).getText()
          productos.append(titulo)
        #precios = list()
          precio = entrada.find('p', {'class': 'product-item__price-wrapper'}).getText()
          precios.append(precio)
      count = count+1

productos

precios

listadePrecios = []
for l in precios:
    aux = l.split()
    listadePrecios.append(aux[3])
print(listadePrecios)

from datetime import date
today = date.today()
dateToday = today.strftime("%d/%m/%Y")

data = {'Productos':productos,
        'Precio': listadePrecios,
        'Fecha': dateToday}
df = pd.DataFrame(data, columns= ['Productos', 'Precio', 'Fecha'])
df.to_csv('Rondina_productos.csv', index = False, header=True)
print (df)

df